var annotated_dup =
[
    [ "std", null, [
      [ "formatter&lt; Color &gt;", "structstd_1_1formatter_3_01_color_01_4.html", "structstd_1_1formatter_3_01_color_01_4" ],
      [ "formatter&lt; HomMatrix &gt;", "structstd_1_1formatter_3_01_hom_matrix_01_4.html", "structstd_1_1formatter_3_01_hom_matrix_01_4" ],
      [ "formatter&lt; Normal &gt;", "structstd_1_1formatter_3_01_normal_01_4.html", "structstd_1_1formatter_3_01_normal_01_4" ],
      [ "formatter&lt; Point &gt;", "structstd_1_1formatter_3_01_point_01_4.html", "structstd_1_1formatter_3_01_point_01_4" ],
      [ "formatter&lt; Vec &gt;", "structstd_1_1formatter_3_01_vec_01_4.html", "structstd_1_1formatter_3_01_vec_01_4" ]
    ] ],
    [ "BRDF", "struct_b_r_d_f.html", "struct_b_r_d_f" ],
    [ "BVHAABB", "struct_b_v_h_a_a_b_b.html", "struct_b_v_h_a_a_b_b" ],
    [ "BVHBin", "struct_b_v_h_bin.html", "struct_b_v_h_bin" ],
    [ "BVHNode", "struct_b_v_h_node.html", "struct_b_v_h_node" ],
    [ "Camera", "struct_camera.html", "struct_camera" ],
    [ "CheckeredPigment", "struct_checkered_pigment.html", "struct_checkered_pigment" ],
    [ "Color", "struct_color.html", "struct_color" ],
    [ "Cube", "struct_cube.html", "struct_cube" ],
    [ "DiffusiveBRDF", "struct_diffusive_b_r_d_f.html", "struct_diffusive_b_r_d_f" ],
    [ "DummyXYZ", "struct_dummy_x_y_z.html", "struct_dummy_x_y_z" ],
    [ "FailingStreamBuf", "class_failing_stream_buf.html", "class_failing_stream_buf" ],
    [ "FlatRenderer", "struct_flat_renderer.html", "struct_flat_renderer" ],
    [ "GrammarError", "struct_grammar_error.html", "struct_grammar_error" ],
    [ "HDRImage", "struct_h_d_r_image.html", "struct_h_d_r_image" ],
    [ "HitRecord", "struct_hit_record.html", "struct_hit_record" ],
    [ "HomMatrix", "struct_hom_matrix.html", "struct_hom_matrix" ],
    [ "IdentifierToken", "struct_identifier_token.html", "struct_identifier_token" ],
    [ "ImagePigment", "struct_image_pigment.html", "struct_image_pigment" ],
    [ "ImageTracer", "struct_image_tracer.html", "struct_image_tracer" ],
    [ "InputStream", "struct_input_stream.html", "struct_input_stream" ],
    [ "InvalidPfmFileFormat", "struct_invalid_pfm_file_format.html", "struct_invalid_pfm_file_format" ],
    [ "KeywordToken", "struct_keyword_token.html", "struct_keyword_token" ],
    [ "LiteralNumberToken", "struct_literal_number_token.html", "struct_literal_number_token" ],
    [ "LiteralStringToken", "struct_literal_string_token.html", "struct_literal_string_token" ],
    [ "Material", "struct_material.html", "struct_material" ],
    [ "Mesh", "struct_mesh.html", "struct_mesh" ],
    [ "Normal", "struct_normal.html", "struct_normal" ],
    [ "OnOffRenderer", "struct_on_off_renderer.html", "struct_on_off_renderer" ],
    [ "OrthogonalCamera", "struct_orthogonal_camera.html", "struct_orthogonal_camera" ],
    [ "Parameters", "struct_parameters.html", "struct_parameters" ],
    [ "PathTracer", "struct_path_tracer.html", "struct_path_tracer" ],
    [ "PCG", "struct_p_c_g.html", "struct_p_c_g" ],
    [ "PerspectiveCamera", "struct_perspective_camera.html", "struct_perspective_camera" ],
    [ "Pigment", "struct_pigment.html", "struct_pigment" ],
    [ "Plane", "struct_plane.html", "struct_plane" ],
    [ "Point", "struct_point.html", "struct_point" ],
    [ "Ray", "struct_ray.html", "struct_ray" ],
    [ "Renderer", "struct_renderer.html", "struct_renderer" ],
    [ "Scene", "struct_scene.html", "struct_scene" ],
    [ "Shape", "struct_shape.html", "struct_shape" ],
    [ "SourceLocation", "struct_source_location.html", "struct_source_location" ],
    [ "SpecularBRDF", "struct_specular_b_r_d_f.html", "struct_specular_b_r_d_f" ],
    [ "Sphere", "struct_sphere.html", "struct_sphere" ],
    [ "StopToken", "struct_stop_token.html", "struct_stop_token" ],
    [ "SymbolToken", "struct_symbol_token.html", "struct_symbol_token" ],
    [ "Token", "struct_token.html", "struct_token" ],
    [ "Transformation", "struct_transformation.html", "struct_transformation" ],
    [ "TriangleIndexes", "struct_triangle_indexes.html", "struct_triangle_indexes" ],
    [ "TrianglePoint", "struct_triangle_point.html", "struct_triangle_point" ],
    [ "UniformPigment", "struct_uniform_pigment.html", "struct_uniform_pigment" ],
    [ "Vec", "struct_vec.html", "struct_vec" ],
    [ "Vec2D", "struct_vec2_d.html", "struct_vec2_d" ],
    [ "World", "struct_world.html", "struct_world" ]
];