/*
* Copyright (c) 2026 Giulia Gogna, Riccardo Piazza.
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * @file Renderer.cppm
 * @brief Rendering algorithms.
 *
 * This module defines the rendering strategies used to evaluate camera rays,
 * ranging from simple visibility tests to recursive Monte Carlo path tracing.
 */

module;

export module Renderer;

import std;
import Pigment;
import Color;
import HDRImage;
import Camera;
import Geometry;
import Shape;
import PCG;
import Material;


// =========================================================================
// BASE RENDERER
// =========================================================================

/**
 * @brief Base class for rendering algorithms.
 *
 * A renderer evaluates a ray and returns the radiance associated with that ray.
 */
export struct Renderer {

    /// Scene to be rendered.
    const World* world;

    /// Radiance returned when a ray does not hit any object.
    Color background_color;

    /**
     * @brief Construct a renderer.
     *
     * @param world Scene to render.
     * @param bg_color Environment radiance.
     */
    Renderer(const World* world, Color bg_color = Color{0.0f, 0.0f, 0.0f}) : world{world}, background_color{bg_color} {}

    /// Virtual destructor
    virtual ~Renderer() = default;

    /**
     * @brief Evaluate the radiance carried by a ray.
     *
     * @param ray Ray to evaluate.
     * @return Radiance associated with the ray.
     */
    [[nodiscard]] virtual Color operator()(const Ray& ray) const = 0;
};

// =========================================================================
// ON/OFF RENDERER (Black and White)
// =========================================================================

/**
 * @brief Visibility renderer.
 *
 * Returns one color for rays that hit an object and another
 * color for rays that miss.
 */
export struct OnOffRenderer : Renderer {

    /// Color returned when an intersection occurs.
    Color hit_color;

    OnOffRenderer(const World* world, Color bg_color = Color{0.0f, 0.0f, 0.0f}, Color hit_color = Color{1.0f, 1.0f, 1.0f})
        : Renderer(world, bg_color), hit_color{hit_color} {}

    [[nodiscard]] Color operator()(const Ray& ray) const override {
        if (world->ray_intersection(ray).has_value()) {
            return hit_color;
        } else {
            return background_color;
        }
    }
};

// =========================================================================
// FLAT RENDERER (Pigment colors)
// =========================================================================

/**
 * @brief Flat-shading renderer.
 *
 * Returns the pigment color associated with the intersected surface
 * without performing any lighting computation.
 */
export struct FlatRenderer : Renderer {
    // Inherit constructors from Renderer
    using Renderer::Renderer;

    [[nodiscard]] Color operator()(const Ray& ray) const override {
        auto hit = world->ray_intersection(ray);

        if (hit.has_value()) {
            const Shape* shape = hit->hitted_shape;

            // Safety check: ensure the shape has a material and a BRDF attached
            if (shape->material && shape->material->brdf) {
                return shape->material->brdf->pigment->get_color(hit->surface_params);
            }

            // Fallback color if the shape has no material attached
            return Color{1.0f, 0.0f, 0.0f};
        }

        return background_color;
    }
};

// =========================================================================
// PATH TRACER (solution of rendering equation)
// =========================================================================

/**
 * @brief Monte Carlo path tracer.
 *
 * Estimates the rendering equation by recursively tracing scattered rays generated by surface BRDFs.
 */
export struct PathTracer : Renderer {

    /// Random number generator used for sampling.
    PCG& pcg;

    /// Number of secondary rays generated per interaction.
    int num_of_rays;

    /// Maximum recursion depth.
    int max_depth;

    /// Depth at which Russian Roulette begins.
    int russian_roulette_limit;

    using Renderer::Renderer;

    /**
     * @brief Monte Carlo path tracer.
     *
     * Estimates the rendering equation by recursively tracing scattered rays generated by surface BRDFs.
     *
     * The implementation supports:
     * - recursive light transport
     * - Monte Carlo integration
     * - Russian Roulette path termination
     *
     * @param pcg Random number generator.
     * @param world Scene to render.
     * @param background_color Environment radiance.
     * @param num_of_rays Number of samples per bounce.
     * @param max_depth Maximum recursion depth.
     * @param russian_roulette_limit Depth at which Russian Roulette starts.
     */
    PathTracer(
        PCG& pcg,
        World* world,
        Color background_color = Color{0.0f, 0.0f, 0.0f},
        int num_of_rays = 10,
        int max_depth = 10,
        int russian_roulette_limit = 3
        ) : Renderer(world, background_color), pcg(pcg), num_of_rays(num_of_rays), max_depth(max_depth), russian_roulette_limit(russian_roulette_limit) {}

    [[nodiscard]] Color operator()(const Ray& ray) const override {

        // Stop recursion once the maximum depth is reached.
        if(ray.depth > max_depth) {
            return Color{0.0f, 0.0f, 0.0f};
        }

        auto hit_record = world->ray_intersection(ray);

        // No intersection: terminate the path and return the background color.
        if (!hit_record.has_value()) {
            return background_color;
        }

        // If the ray intersects something, we need to solve the rendering equation at the point of intersection
        auto hit_material = hit_record->hitted_shape->material;

        Color hit_color = hit_material->brdf->pigment->get_color(hit_record->surface_params); // Surface reflectance.
        Color emitted_radiance = hit_material->emitted_radiance->get_color(hit_record->surface_params); // Self-emitted radiance.

        // ---------------------------------------------------------------------------------------------------
        // Russian Roulette: triggered only if the ray has been reflected at least russian_roulette_limit
        // ---------------------------------------------------------------------------------------------------

        // Estimate a continuation probability from the surface reflectance.
        float hit_color_lum = std::max({hit_color.r, hit_color.g, hit_color.b});

        if (ray.depth > russian_roulette_limit) { // First reflections are always preserved
            float q = std::max(0.05f, 1.0f-hit_color_lum);
            if (pcg.random_float() > q) {
                // Continue the path and compensate for discarded samples to keep the estimator unbiased.
                hit_color *= 1.0f/(1.0f - q);
            } else {
                // Terminate the path.
                return emitted_radiance;
            }
        }

        // Estimate indirect radiance by recursively tracing scattered rays.

        // ---------------------------------------------------------------------------------------------------
        // Monte Carlo estimate of indirect radiance.
        // ---------------------------------------------------------------------------------------------------

        Color cum_radiance = Color{0.0f, 0.0f, 0.0f};

        if (hit_color_lum > 0.0f) { // Only do costly recursions if it's worth it
            for (int ray_index = 0; ray_index < num_of_rays; ray_index++) {

                // Sample a scattered direction from the BRDF.
                Ray new_ray = hit_material->brdf->scatter_ray(
                    pcg,
                    hit_record->ray.direction,
                    hit_record->hit_point,
                    hit_record->hit_normal,
                    hit_record->ray.depth + 1
                );

                // Recursively evaluate incoming radiance.
                Color new_radiance = (*this)(new_ray);
                cum_radiance += hit_color * new_radiance; // Add the radiance of the new ray, obtained by recursion, to the current radiance
            }
        }

        // Direct emission + average indirect contribution.
        return emitted_radiance + cum_radiance * 1.0f / num_of_rays;
    }
};